# Generated by Django 5.2.11 on 2026-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enable email')),
                ('backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console (debug)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=100, verbose_name='Email backend')),
                ('host', models.CharField(default='localhost', max_length=255, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Password')),
                ('security', models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=10, verbose_name='Security')),
                ('from_email', models.EmailField(default='noreply@example.com', max_length=254, verbose_name='From email')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout (seconds)')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
